---
name: java-language-server
description: Java language server using the Java compiler API.
homepage: https://github.com/ozzy-cox/java-language-server
licenses:
  - MIT
languages:
  - Java
categories:
  - LSP
  - DAP

source:
  # renovate:datasource=github-tags
  id: pkg:github/ozzy-cox/java-language-server@master
  build:
    - target: [darwin_x64, darwin_arm64]
      run: |
        ./scripts/link_mac.sh
        mvn package -DskipTests
      bin:
        lsp: exec:dist/lang_server_mac.sh
        dap: exec:dist/debug_adapter_mac.sh
    - target: linux
      run: |
        ./scripts/link_linux.sh
        mvn package -DskipTests
      bin:
        lsp: exec:dist/lang_server_linux.sh
        dap: exec:dist/debug_adapter_linux.sh
    - target: win
      run: |
        bash .\scripts\link_windows.sh
        mvn package -DskipTests
      bin:
        lsp: dist/lang_server_windows.cmd
        dap: dist/debug_adapter_windows.cmd

schemas:
  lsp: vscode:https://raw.githubusercontent.com/ozzy-cox/java-language-server/{{version}}/package.json

bin:
  java-language-server: "{{source.build.bin.lsp}}"
  java-language-server-debugger: "{{source.build.bin.dap}}"
